version: '3.8'

services:
  rag-api:
    build: .
    container_name: rag-api
    restart: unless-stopped
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    networks:
      - rag-network
    depends_on:
      - nginx

  nginx:
    image: nginx:alpine
    container_name: rag-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/api-rag.onexus.tech.conf:/etc/nginx/sites-available/api-rag.onexus.tech.conf
      - ./ssl:/etc/nginx/ssl
      - ./logs/nginx:/var/log/nginx
    networks:
      - rag-network
    depends_on:
      - rag-api

networks:
  rag-network:
    driver: bridge 